kind: pipeline
name: default

steps:
- name: Composer Install
  image: composer:latest
  commands:
  -  composer install
- name: Translations
  image: lucor/php7-cli:latest
  commands:
  - php bin/install.php translations develop
- name: Node, Bower Grunt
  image: digitallyseamless/nodejs-bower-grunt:latest
  commands:
  - npm install && bower install && grunt
- name: Notifications
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: telegram_api
    to: 
      from_secret: telegram_user
    message: >
      {{#success build.status}}
        build {{build.number}}, based on commit {{truncate build.sha 8}} on branch {{commit.branch}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}