kind: pipeline
name: default

steps:
- name: Composer Install
  image: composer:latest
  commands:
  -  composer install
- name: Translations
  image: lucor/php7-cli:latest
  commands:
  - php bin/install.php translations develop
- name: Node, Bower Grunt
  image: digitallyseamless/nodejs-bower-grunt:latest
  commands:
  - npm install && bower install && grunt
  
  
  telegram:
    image: appleboy/drone-telegram
    token: 782307972:AAFkuv7FEfBFviWFcRic38Tya6O4bHj0bZQ
    to: 43672802
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}