kind: pipeline
name: default

steps:
- name: Composer Install
  image: composer
  commands:
  -  composer install
  
- name: Translations
  image: lucor/php7-cli
  commands:
  - php bin/install.php translations develop
  
- name: Node, Bower Grunt
  image: digitallyseamless/nodejs-bower-grunt
  commands:
  - npm install && bower install && grunt j
  
- name: Database Setup
  image: virtualforce/php7.1-pdo-mysql-ci:1.1
  commands:
  - echo MYSQL_HOST_NAME="Database" >> application/config/.env
  - echo MYSQL_USERNAME="root"  >> application/config/.env
  - echo MYSQL_PASSWORD=""  >> application/config/.env
  - echo MYSQL_DB_NAME="neptune" >> application/config/.env
  - vendor/bin/phinx migrate

- name: notify
  image: appleboy/drone-telegram
  when:
    status:
    - success
    - failure
  settings:
    token:
      from_secret: telegram_api
    to:
      from_secret: telegram_user
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Well Done.
      {{else}}
        build {{build.number}} failed.  Please fix me.
      {{/success}}


services:
- name: Database
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: neptune
    
