kind: pipeline
name: default

steps:
- name: Composer Install
  image: composer
  commands:
  -  composer install
  
- name: Translations
  image: lucor/php7-cli
  commands:
  - php bin/install.php translations develop
  
- name: Node, Bower Grunt
  image: digitallyseamless/nodejs-bower-grunt
  commands:
  - npm install && bower install && grunt
  
- name: Database Setup
  image: virtualforce/php7.1-pdo-mysql-ci:1.1
  commands:
  - echo MYSQL_HOST_NAME="Database" >> application/config/.env
  - echo MYSQL_USERNAME="root"  >> application/config/.env
  - echo MYSQL_PASSWORD=""  >> application/config/.env
  - echo MYSQL_DB_NAME="neptune" >> application/config/.env
  - vendor/bin/phinx migrate

- name: Login 2
  image: php:7.2.19-apache-stretch
  commands:
   - apt-get update -y
   - service apache2 stop
   - ln -s /drone/src/*[^public] /var/www
   - rm -rf /var/www/html 
   - ln -nsf /drone/src/public /var/www/html
   - chown www-data:www-data /drone/src/application
   - service apache2 start
   - a2enmod rewrite
   - echo "date.timezone = \"Europe/London\"" > /usr/local/etc/php/conf.d/timezone.ini  
   - apt-get install libicu-dev zlib1g-dev libgd-dev -y
   - docker-php-ext-install mysqli bcmath intl gd
   - vendor/bin/codecept run

- name: Login Tests
  image: virtualforce/php7.1-pdo-mysql-ci:1.1
  commands:
    - vendor/bin/codecept run
    
    
- name: notify
  image: appleboy/drone-telegram
  when:
    status:
    - success
    - failure
  settings:
    token:
      from_secret: telegram_api
    to:
      from_secret: telegram_user
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Well Done.
      {{else}}
        build {{build.number}} failed.  Please fix me.
      {{/success}}


services:
- name: Database
  image: mariadb:10.3.15
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: neptune
