kind: pipeline
name: default

steps:
- name: Composer Install
  image: composer:latest
  commands:
  -  composer install
- name: Translations
  image: lucor/php7-cli:latest
  commands:
  - php bin/install.php translations develop
- name: Node, Bower Grunt
  image: digitallyseamless/nodejs-bower-grunt:latest
  commands:
  - npm install && bower install && grunt package