kind: pipeline
name: default

steps:
- name: Composer Install
  image: composer
  commands:
  -  composer install
- name: Translations
  image: lucor/php7-cli
  commands:
  - php bin/install.php translations develop
- name: Node, Bower Grunt
  image: digitallyseamless/nodejs-bower-grunt
  commands:
  - npm install && bower install && grunt
- name: Database Setup
  image: virtualforce/php7.1-pdo-mysql-ci:1.1
  commands:
  - echo MYSQL_HOST_NAME="database" >> application/config/.env
  - echo MYSQL_USERNAME="root"  >> application/config/.env
  - echo MYSQL_PASSWORD=""  >> application/config/.env
  - echo MYSQL_DB_NAME="neptune" >> application/config/.env
  - php7enmod -s cli pdo_mysql
  - pwd
  - cat application/config/.env
  - vendor/bin/phinx migrate

- name: Notifications
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_api
    to:
      from_secret: telegram_user
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}


services:
- name: database
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: neptune
    
